[package]
name = "zjit-bindgen"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bindgen = "0.71.1"
env_logger = "0.11.5"

[workspace]
