name: Auto Review PR
on:
  pull_request_target:
    types: [opened, ready_for_review, reopened]
    branches: [master]

permissions:
  contents: read

jobs:
  auto-review-pr:
    name: Auto Review PR
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'ruby/ruby' && github.base_ref == 'master' }}

    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.1

      - uses: ruby/setup-ruby@90be1154f987f4dc0fe0dd0feedac9e473aa4ba8 # v1.286.0
        with:
          ruby-version: '3.4'
          bundler: none

      - name: Auto Review PR
        run: ruby tool/auto_review_pr.rb "$GITHUB_PR_NUMBER"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
