on:
  check_suite:
    type: ['completed']
name: Cirrus CI failure notification

permissions:
  contents: read

jobs:
  cirrus-notify:
    name: After Cirrus CI Failure
    if: >-
      github.event.check_suite.app.name == 'Cirrus CI'
      && github.event.check_suite.conclusion != 'success'
      && github.event.check_suite.conclusion != 'cancelled'
      && github.event.check_suite.conclusion != 'skipped'
      && github.event.check_suite.head_branch == 'master'
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@52ce92ce3185e00e2425f043c3e9509121929aea # v2.x
        id: get_failed_check_run
        with:
          route: GET /repos/${{ github.repository }}/check-suites/${{ github.event.check_suite.id }}/check-runs?status=completed
          mediaType: '{"previews": ["antiope"]}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump check_runs
        env:
          CHECK_RUNS: ${{ steps.get_failed_check_run.outputs.data }}
        run: echo "$CHECK_RUNS"
      - uses: ruby/action-slack@b6882ea6ef8f556f9f9af9ec1220d3f1ced74acf # v3.0.0
        with:
          payload: |
            {
              "ci": "Cirrus CI",
              "env": "Cirrus CI",
              "url": "${{ fromJson(steps.get_failed_check_run.outputs.data).check_runs[0].html_url }}",
              "commit": "${{ github.event.check_suite.head_commit.id }}",
              "branch": "${{ github.event.check_suite.head_branch }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SIMPLER_ALERTS_URL }} # ruby-lang slack: ruby/simpler-alerts-bot
