# from https://github.com/gofiber/swagger/blob/main/.github/workflows/dependabot_automerge.yml
name: Dependabot auto-merge
on:
  pull_request_target:

jobs:
  automerge:
    runs-on: ubuntu-latest

    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}

    steps:
      - name: Dependabot metadata
        uses: dependabot/fetch-metadata@d7267f607e9d3fb96fc2fbe83e0af444713e90b7 # v2.3.0
        id: metadata

      - name: Wait for status checks
        uses: lewagon/wait-on-check-action@ccfb013c15c8afb7bf2b7c028fb74dc5a068cccc # v1.3.4
        with:
          repo-token: ${{ secrets.MATZBOT_GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          check-regexp: 'make \(check, .*\)'
          wait-interval: 30

      - name: Auto-merge for Dependabot PRs
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-minor' || steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.MATZBOT_GITHUB_TOKEN }}
