name: doxygen
on:
  schedule:
    - cron: '0 * * * *'
  pull_request:
    branches:
      - '*'
jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - name: Install libraries
        run: |
          set -x
          sudo sed /etc/apt/sources.list -e "s/^# deb-src/deb-src/g" -i
          sudo apt-get update
          sudo apt-get install ruby2.5 doxygen graphviz
          sudo apt-get build-dep ruby2.5

      # Not using official actions/checkout because it's unstable and sometimes doesn't work for a fork.
      - name: Checkout ruby/ruby
        run: git clone --depth=1 https://github.com/ruby/ruby . && git reset --hard "$GITHUB_SHA"
        env:
          GITHUB_SHA: ${{ github.sha }}
        if: github.event_name == 'schedule'
      - name: Checkout a pull request
        run: git clone --depth=1 "--branch=$GITHUB_BRANCH" "https://github.com/${GITHUB_REPO}" . && git reset --hard "$GITHUB_REV"
        env:
          GITHUB_REV: ${{ github.event.pull_request.head.sha }}
          GITHUB_BRANCH: ${{ github.event.pull_request.head.ref }}
          GITHUB_REPO: ${{ github.event.pull_request.head.repo.full_name }}
        if: github.event_name == 'pull_request'

      - name: Fixed world writable dirs
        run: |
          chmod go-w $HOME
          sudo chmod -R go-w /usr/share
      - run: autoconf
      - name: Configure
        run: ./configure
      - name: Generate Doxyfile
        run: make Doxyfile
      - name: Run Doxygen
        run: doxygen
      - name: Upload results
        run: |
          aws s3 sync doc/capi/html/ s3://rubyci/doxygen-latest-html
        env:
          GITHUB_SHA: ${{ github.sha }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        if: github.event_name == 'schedule'
