name: Publish Ruby packages

on:
  repository_dispatch:
    types:
      - release
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the Ruby package to release'
        required: true
        default: '3.3.4'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Store Ruby version
        run: |
          echo "RUBY_VERSION=${{ github.event.client_payload.version || github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Copy draft package `/tmp` to `/pub` directory
        run: tool/release.sh ${{ env.RUBY_VERSION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.FTP_R_L_O_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.FTP_R_L_O_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2

      # TODO
      # - name: Create a release on GitHub

      - name: Update versions index
        run: |
          curl -L -X POST \
            -H "Authorization: Bearer ${{ secrets.MATZBOT_GITHUB_WORKFLOW_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ruby/actions/dispatches \
            -d '{"event_type": "update_index"}'

      - name: Set latest flag for Ruby 3.3
        if: contains(${{ env.RUBY_VERSION }}, '3.3.')
        run: |
          echo "LATEST=true" >> $GITHUB_ENV

      - name: Build and push Docker images
        run: |
          curl -L -X POST \
            -H "Authorization: Bearer ${{ secrets.MATZBOT_GITHUB_WORKFLOW_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ruby/docker-images/dispatches \
            -d '{"event_type": "build", "client_payload": {"ruby_version": "${{ env.RUBY_VERSION }}", "arch": "amd64", "latest": "${{ env.LATEST }}"}}'

      - name: Build snapcraft packages
        run: |
          curl -L -X POST \
            -H "Authorization: Bearer ${{ secrets.MATZBOT_GITHUB_WORKFLOW_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ruby/snap.ruby/dispatches \
            -d '{"event_type": "build", "client_payload": {"ruby_version": "${{ env.RUBY_VERSION }}"}}'

      - name: Update all-ruby definition
        run: |
          curl -L -X POST \
            -H "Authorization: Bearer ${{ secrets.MATZBOT_GITHUB_WORKFLOW_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ruby/all-ruby/dispatches \
            -d '{"event_type": "update"}'
