name: Rubyspec Version Guards Check

on:
  push:
    paths:
      - 'spec/**'
      - '!spec/*.md'
  pull_request:
    paths-ignore:
      - 'spec/**'
      - '!spec/*.md'
  merge_group:
    paths-ignore:
      - 'spec/**'
      - '!spec/*.md'

concurrency:
  group: ${{ github.workflow }} / ${{ startsWith(github.event_name, 'pull') && github.ref_name || github.sha }}
  cancel-in-progress: ${{ startsWith(github.event_name, 'pull') }}

permissions:
  contents: read

jobs:
  rubyspec:
    name: Rubyspec

    runs-on: ubuntu-20.04

    if: >-
      ${{!(false
      || contains(github.event.head_commit.message, '[DOC]')
      || contains(github.event.pull_request.title, '[DOC]')
      || contains(github.event.pull_request.labels.*.name, 'Documentation')
      || (github.event_name == 'push' && github.actor == 'dependabot[bot]')
      )}}

    strategy:
      matrix:
        # Specs from ruby/spec should still run on all supported Ruby versions.
        # This also ensures the needed ruby_version_is guards are there, see spec/README.md.
        ruby:
          - ruby-3.0
          - ruby-3.1
          - ruby-3.2

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939 # v1.152.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none

      - run: gem install webrick

      - run: ruby ../mspec/bin/mspec
        working-directory: spec/ruby
        env:
          CHECK_LEAKS: true

      - uses: ./.github/actions/slack
        with:
          label: ${{ matrix.ruby }}
          SLACK_WEBHOOK_URL: ${{ secrets.SIMPLER_ALERTS_URL }} # ruby-lang slack: ruby/simpler-alerts-bot
        if: ${{ failure() && github.event_name == 'push' }}
