---
version: "{build}"
clone_depth: 5
environment:
  matrix:
    - RUBY_VERSION: 23-x64
install:
  - SET PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - ruby --version
  - git clone https://github.com/ruby/mspec.git ../mspec
build: off
test_script:
  - SET CHECK_LEAKS=true
  - ../mspec/bin/mspec -ff command_line language core library
branches:
  only:
    - master
    - /^try/
